### ISSUE TITLE
Theme for the site

### ISSUE THREAD

**Issue by ccarouge** [ACCESS-NRI/ACCESSHub#1]
ReadTheDocs default theme is not necessarily the best for our purpose. RTD supports Sphinx and Mkdocs which both have several themes available.

Sphinx themes: https://sphinx-themes.org/
Mkdocs themes: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes

**Comment by ccarouge** [comment]
For Sphinx, I like Furo. It's simple but it has colours, all the items seem to work well, good navigation.

**Comment by aidanheerdegen** [comment]
So many! I can mostly just see ones that won’t work, but there seem a lot that look nice. Material is very clean, but it may not expose the navigation enough.

**Comment by ccarouge** [comment]
I thought DocuMatt looked interesting until I realised nothing is in colour except the headers! Yikes. Warning blocks or note blocks are simply on grey background.

**Comment by aidanheerdegen** [comment]
I like some of the MkDocs themes:

- [Material](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes#material-for-mkdocs-): [activity report](https://kandi.openweaver.com/typescript/squidfunk/mkdocs-material)
- [Windmill](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes#windmill-): [activity report](https://kandi.openweaver.com/css/gristlabs/mkdocs-windmill)
- [Bootstrap](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes#bootstrap-): [activity report](https://kandi.openweaver.com/css/mkdocs/mkdocs-bootstrap)
- [Bootstrap4](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes#bootstrap4-): [activity report](https://kandi.openweaver.com/css/mkdocs/mkdocs-bootstrap4)

In terms of usage and support Material is the stand-out from those four.

**Comment by ccarouge** [comment]
Material in MkDocs looks really really good!

**Comment by aidanheerdegen** [comment]
Material is very well supported and well used too.

**Comment by ccarouge** [comment]
Just a question that's not completely relevant to ACCESSHub: for documentation sites that require API documentation, should they rely on Sphinx instead of MkDocs? Simply I see API in the Sphinx themes but not in MkDocs.

**Comment by aidanheerdegen** [comment]
I think Sphinx is clearly the tool of choice for API docs. There is a plugin that offers API support for MkDocs and supports dumpy and google style docstrings

https://mkapi.daizutabi.net

So sphinx allows (prefers) docstrings to be written in RST, so it can be completely general. Would need to check if using a specific style of docstring is compatible with your use case, which is CABLE docs I guess?

Here is a nice description of using MkDocs (and they seem to really like it)

https://chrieke.medium.com/documenting-a-python-package-with-code-reference-via-mkdocs-material-b4a45197f95b

And a couple more really slick looking sights using material and MkDocs

https://sdk.up42.com

https://ludwig-ai.github.io/ludwig-docs/0.5/

The template that makes the Ludwig one look so cool is [here](https://github.com/ludwig-ai/ludwig-docs/blob/master/custom/landing.html)

**Comment by ccarouge** [comment]
Let's start with Material for Mkdocs then.
